source 'https://rubygems.org/'

gem 'rubydoop', :path => '../../..'
gem 'paint'
gem 'puck', :git => 'git@github.com:jowl/puck.git', :branch => 'default-entrypoint'
gem 'jruby-jars', "= #{JRUBY_VERSION}"

group :development do
  gem 'rake'
  gem 'pry'
end